### PR TITLE
Revert import change

### PR DESCRIPTION
**Pull request by jae-lee**
Ended up breaking imports when updating snapshots

### CODE REVIEW

**Review by dmastylo — APPROVED** [review]

**Comment by erichurkman** [comment]
Do you want to bump the version?

**Comment by jae-lee** [comment]
@erichurkman Haha I rebased and bumped the version, we should be good

**Review by erichurkman — APPROVED** [review]

**Comment by erichurkman** [comment]
Approved, can you merge and publish a new version?

You will probably have to edit the index file by hand  unless you can figure out why s3pypi is being dumb. Or we're misusing it?

**Comment by jae-lee** [comment]
Closed, because this didn't fix everything. Details in #proxy-plumbers

**Pull request closed without merging**
